# Generated by Django 5.0 on 2024-01-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_productattachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
